"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401  (referenced by autogenerated types)
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerated column definitions render custom types by their full module
# path (``hedgelab.db.base.Money``), so the package itself must be importable
# here, not just the names.
import hedgelab.db.base  # noqa: F401
from hedgelab.db.base import JSONType, Money, UTCDateTime  # noqa: F401

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
