"""initial schema

Revision ID: ac34f66750a6
Revises: 
Create Date: 2026-09-08 13:25:17.006735+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401  (referenced by autogenerated types)
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerated column definitions render custom types by their full module
# path (``hedgelab.db.base.Money``), so the package itself must be importable
# here, not just the names.
import hedgelab.db.base  # noqa: F401
from hedgelab.db.base import JSONType, Money, UTCDateTime  # noqa: F401

revision: str = 'ac34f66750a6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity_time', 'audit_logs', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_table('configuration_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=48), nullable=True),
    sa.Column('fill_exec_id', sa.String(length=48), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_order_id'), 'fees', ['order_id'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_ccy', sa.String(length=16), nullable=False),
    sa.Column('quote_ccy', sa.String(length=16), nullable=False),
    sa.Column('rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fx_pair_time', 'fx_rates', ['base_ccy', 'quote_ccy', 'timestamp'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('venue_kind', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('quote_asset', sa.String(length=32), nullable=False),
    sa.Column('settlement_asset', sa.String(length=32), nullable=False),
    sa.Column('underlying_key', sa.String(length=32), nullable=False),
    sa.Column('quantity_unit', sa.String(length=16), nullable=False),
    sa.Column('settlement_style', sa.String(length=16), nullable=False),
    sa.Column('contract_size', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('contract_multiplier', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('units_per_contract', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('units_per_lot', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('tick_size', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('tick_value', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('min_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('max_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('quantity_step', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('quantity_precision', sa.Integer(), nullable=False),
    sa.Column('max_leverage', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('margin_model', sa.String(length=32), nullable=False),
    sa.Column('initial_margin_rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('maintenance_margin_rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('maker_fee_bps', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('taker_fee_bps', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('fee_currency', sa.String(length=32), nullable=False),
    sa.Column('typical_spread_bps', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('slippage_bps_per_unit_liquidity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_model', sa.String(length=32), nullable=False),
    sa.Column('funding_interval_hours', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('baseline_funding_rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('swap_long_points', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('swap_short_points', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('swap_triple_weekday', sa.Integer(), nullable=False),
    sa.Column('trading_hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allow_long', sa.Boolean(), nullable=False),
    sa.Column('allow_short', sa.Boolean(), nullable=False),
    sa.Column('price_source', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'symbol', name='uq_instrument_venue_symbol')
    )
    op.create_index('ix_instrument_underlying', 'instruments', ['underlying_key'], unique=False)
    op.create_table('margin_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('balance', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('equity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('used_margin', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('free_margin', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('margin_level', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('maintenance_margin', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('unrealized_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_margin_venue_time', 'margin_snapshots', ['venue', 'timestamp'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('bid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('ask', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('mid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('last', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('spread', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('volume', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_key_time', 'market_data', ['venue', 'symbol', 'timestamp'], unique=False)
    op.create_table('pnl_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('pair_name', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('gross_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('trading_fees', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_received', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_paid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('swap_financing', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('spread_cost', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('slippage_cost', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('fx_impact', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('net_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('realized_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('unrealized_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pnl_scope_time', 'pnl_records', ['scope', 'timestamp'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('pair_name', sa.String(length=128), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('threshold', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('cycle_id', sa.String(length=48), nullable=True),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_event_level_time', 'risk_events', ['level', 'timestamp'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_event_kind_time', 'system_events', ['kind', 'timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('instrument_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_instrument_id', sa.Integer(), nullable=False),
    sa.Column('hedge_instrument_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hedge_instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('source_instrument_id', 'hedge_instrument_id', name='uq_mapping_pair')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=48), nullable=False),
    sa.Column('client_order_id', sa.String(length=48), nullable=False),
    sa.Column('cycle_id', sa.String(length=48), nullable=True),
    sa.Column('leg', sa.String(length=16), nullable=True),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('price', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('average_price', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('reference_price', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_order_cycle', 'orders', ['cycle_id'], unique=False)
    op.create_index('ix_order_venue_symbol', 'orders', ['venue', 'symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('average_entry', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('realized_pnl', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_paid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('funding_received', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('updated_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'symbol', name='uq_position_venue_symbol')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exec_id', sa.String(length=48), nullable=False),
    sa.Column('order_row_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=48), nullable=False),
    sa.Column('quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('price', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('fee', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('slippage', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=False),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_row_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exec_id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_table('funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rate', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('interval_hours', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('amount', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hedge_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=False),
    sa.Column('target_ratio', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('tolerance_bps', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('rebalance_enabled', sa.Boolean(), nullable=False),
    sa.Column('rebalance_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('rebalance_min_notional', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('optimizer_mode', sa.String(length=24), nullable=False),
    sa.Column('optimizer_priority', sa.String(length=32), nullable=False),
    sa.Column('optimizer_search_steps', sa.Integer(), nullable=False),
    sa.Column('optimizer_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_notional', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('max_position', hedgelab.db.base.Money(precision=38, scale=18), nullable=True),
    sa.Column('risk_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['instrument_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hedge_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=48), nullable=False),
    sa.Column('pair_name', sa.String(length=128), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('hedge_key', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=False),
    sa.Column('source_target_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('hedge_target_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('source_filled_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('hedge_filled_quantity', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('hedge_ratio', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('residual_exposure', hedgelab.db.base.Money(precision=38, scale=18), nullable=False),
    sa.Column('source_order_id', sa.String(length=48), nullable=True),
    sa.Column('hedge_order_id', sa.String(length=48), nullable=True),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['hedge_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapping_id'], ['instrument_mappings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_index('ix_cycle_state_created', 'hedge_cycles', ['state', 'created_at'], unique=False)
    op.create_index(op.f('ix_hedge_cycles_correlation_id'), 'hedge_cycles', ['correlation_id'], unique=False)
    op.create_table('hedge_cycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_row_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=48), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=True),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', hedgelab.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_row_id'], ['hedge_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_row_id', 'sequence', name='uq_cycle_event_sequence')
    )
    op.create_index('ix_cycle_event_time', 'hedge_cycle_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_hedge_cycle_events_cycle_id'), 'hedge_cycle_events', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hedge_cycle_events_cycle_id'), table_name='hedge_cycle_events')
    op.drop_index('ix_cycle_event_time', table_name='hedge_cycle_events')
    op.drop_table('hedge_cycle_events')
    op.drop_index(op.f('ix_hedge_cycles_correlation_id'), table_name='hedge_cycles')
    op.drop_index('ix_cycle_state_created', table_name='hedge_cycles')
    op.drop_table('hedge_cycles')
    op.drop_table('hedge_configs')
    op.drop_table('funding')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('positions')
    op.drop_index('ix_order_venue_symbol', table_name='orders')
    op.drop_index('ix_order_cycle', table_name='orders')
    op.drop_table('orders')
    op.drop_table('instrument_mappings')
    op.drop_table('users')
    op.drop_index('ix_system_event_kind_time', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('scenario_runs')
    op.drop_index('ix_risk_event_level_time', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_pnl_scope_time', table_name='pnl_records')
    op.drop_table('pnl_records')
    op.drop_index('ix_market_data_key_time', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_margin_venue_time', table_name='margin_snapshots')
    op.drop_table('margin_snapshots')
    op.drop_index('ix_instrument_underlying', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_fx_pair_time', table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_fees_order_id'), table_name='fees')
    op.drop_table('fees')
    op.drop_table('emergency_actions')
    op.drop_table('configuration_changes')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
